from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import polars as pl


class PyExpr:
    def alias(self, name: str) -> PyExpr: ...
    def collect_inputs(self) -> set[str]: ...
    def output_name(self) -> str | None: ...
    def replace_inputs(self, names: dict[str, str]) -> PyExpr: ...
    def neg(self) -> PyExpr: ...
    def abs(self) -> PyExpr: ...
    def log(self) -> PyExpr: ...
    def sign(self) -> PyExpr: ...
    def rank(self) -> PyExpr: ...
    def scale(self, scale_to: float = 1.0) -> PyExpr: ...
    def delay(self, days: int) -> PyExpr: ...
    def delta(self, days: int) -> PyExpr: ...
    def ts_sum(self, days: int) -> PyExpr: ...
    def ts_mean(self, days: int) -> PyExpr: ...
    def product(self, days: int) -> PyExpr: ...
    def ts_min(self, days: int) -> PyExpr: ...
    def ts_max(self, days: int) -> PyExpr: ...
    def ts_argmin(self, days: int) -> PyExpr: ...
    def ts_argmax(self, days: int) -> PyExpr: ...
    def ts_rank(self, days: int) -> PyExpr: ...
    def ts_rank_raw(self, days: int) -> PyExpr: ...
    def ts_std(self, days: int) -> PyExpr: ...
    def slope(self, days: int) -> PyExpr: ...
    def rsquare(self, days: int) -> PyExpr: ...
    def resi(self, days: int) -> PyExpr: ...
    def quantile(self, days: int, q: float) -> PyExpr: ...
    def decay_linear(self, days: int) -> PyExpr: ...
    def __add__(self, other: PyExpr) -> PyExpr: ...
    def __sub__(self, other: PyExpr) -> PyExpr: ...
    def __mul__(self, other: PyExpr) -> PyExpr: ...
    def __truediv__(self, other: PyExpr) -> PyExpr: ...
    def __neg__(self) -> PyExpr: ...
    def __lt__(self, other: PyExpr) -> PyExpr: ...
    def __gt__(self, other: PyExpr) -> PyExpr: ...
    def __le__(self, other: PyExpr) -> PyExpr: ...
    def __ge__(self, other: PyExpr) -> PyExpr: ...
    def __eq__(self, other: object) -> PyExpr: ...  # type: ignore[override]


def roundtrip(df: pl.DataFrame) -> pl.DataFrame: ...


def compute_alphas(
    df: pl.DataFrame,
    symbol_col: str,
    time_col: str,
    alphas: Sequence[PyExpr],
    output_path: str | None = None,
) -> pl.DataFrame | dict[str, Any]: ...


def with_alphas(
    df: pl.DataFrame,
    symbol_col: str,
    time_col: str,
    alphas: Sequence[PyExpr],
) -> pl.DataFrame: ...


def with_labels(
    df: pl.DataFrame,
    symbol_col: str,
    time_col: str,
    horizons: Sequence[int],
    entry_lag: int = 1,
    entry_col: str = "close",
    exit_col: str = "close",
    tradable_col: str | None = None,
    calendar: pl.Series | None = None,
) -> pl.DataFrame: ...


def col(name: str) -> PyExpr: ...
def lit(value: float) -> PyExpr: ...
def min(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def max(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def power(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def signed_power(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def correlation(lhs: PyExpr, rhs: PyExpr, days: int) -> PyExpr: ...
def covariance(lhs: PyExpr, rhs: PyExpr, days: int) -> PyExpr: ...
def group_rank(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def group_neutralize(lhs: PyExpr, rhs: PyExpr) -> PyExpr: ...
def where_(cond: PyExpr, when_true: PyExpr, when_false: PyExpr) -> PyExpr: ...
def worldquant_alpha101(
    input_alias: dict[str, str],
    alphas: Sequence[str] | None = None,
) -> list[PyExpr]: ...
def qlib_alpha158(
    input_alias: dict[str, str],
    alphas: Sequence[str] | None = None,
) -> list[PyExpr]: ...
